# Generated by Django 4.2.27 on 2026-01-30 11:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20, unique=True, verbose_name='Số hiệu tuyến')),
                ('name', models.CharField(max_length=200, verbose_name='Tên tuyến')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('start_point', models.CharField(max_length=200, verbose_name='Điểm đầu')),
                ('end_point', models.CharField(max_length=200, verbose_name='Điểm cuối')),
                ('operating_hours', models.CharField(default='05:00 - 22:00', max_length=100, verbose_name='Giờ hoạt động')),
                ('frequency', models.CharField(default='10-15 phút/chuyến', max_length=50, verbose_name='Tần suất')),
                ('ticket_price', models.DecimalField(decimal_places=0, default=7000, max_digits=10, verbose_name='Giá vé (VNĐ)')),
                ('color', models.CharField(default='#3388ff', max_length=7, verbose_name='Màu tuyến')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Đường đi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuyến xe buýt',
                'verbose_name_plural': 'Tuyến xe buýt',
                'ordering': ['route_number'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trạm')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã trạm')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí')),
                ('has_shelter', models.BooleanField(default=False, verbose_name='Có mái che')),
                ('has_bench', models.BooleanField(default=False, verbose_name='Có ghế ngồi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trạm dừng',
                'verbose_name_plural': 'Trạm dừng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Thứ tự dừng')),
                ('distance_from_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Khoảng cách từ điểm đầu (km)')),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời gian ước tính (phút)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busroute', verbose_name='Tuyến')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop', verbose_name='Trạm dừng')),
            ],
            options={
                'verbose_name': 'Điểm dừng trên tuyến',
                'verbose_name_plural': 'Điểm dừng trên tuyến',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order'), ('route', 'stop')},
            },
        ),
    ]
